### PR TITLE
providers/saml: send logoutResponse on sp-init logout

### LINKED ISSUE #7137: Authentik should send a SAML LogoutResponse
**Describe the bug**
According to the SAML standard (https://www.oasis-open.org/committees/download.php/56783/sstc-saml-profiles-errata-2.0-wd-07-diff.pdf ) line 1409 authentik must send a LogoutResponse
Quote:
_The session participant/authority MUST process the <LogoutRequest> message as defined in
[SAMLCore]. After processing the message or upon encountering an error, the entity MUST issue a
<LogoutResponse> message containing an appropriate status code to the requesting identity provider
to complete the SAML protocol exchange._

For some SP's this leads to problems terminating there own sessions. Resulting in users seeing the authentik logout window but the sp sessions stays open.

**To Reproduce**
Create  a SAML Provider. 
Log into SP.
Start SAML tracer
Logout of SP  
Get Redirect to authentik and shown the logout page.
Observe that no logout response has been send.

**Expected behavior**
Authentik should follow the SAML standard wich states that authetnik MUST send a LogoutResponse.

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.8.3
- Deployment: Docker

**Additional context**

### PR DESCRIPTION
**Pull request by PeshekDotDev**
## Details

This PR automatically sends a logoutResponse when logging out of a samlprovider via the SP

Closes #7137 

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [x] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make docs`)

### CODE REVIEW

**Review by GirlBossRush — APPROVED** [review]

File: web/src/flow/providers/saml/NativeLogoutStage.ts [hunk 1]
```diff
@@ -77,21 +77,33 @@ export class NativeLogoutStage extends BaseStage<
 
         // For POST binding, render auto-submit form
         if (this.challenge.binding === SAMLBindingsEnum.Post) {
+            const messageKey = this.challenge.samlResponse ? "response" : "request";
             return html`<ak-flow-card .challenge=${this.challenge} loading>
                 <span slot="title"
-                    >${msg(str`Posting logout request to SAML provider: ${providerName}`)}</span
+                    >${msg(
+                        str`Posting logout ${messageKey} to SAML provider: ${providerName}`,
+                    )}</span
```
Comment (BeryJu) [inline web/src/flow/providers/saml/NativeLogoutStage.ts]: Should be separate strings instead to better support translation (for the `messageKey`

File: web/src/flow/providers/IFrameLogoutStage.ts [hunk 2]
```diff
@@ -28,6 +28,8 @@ interface LogoutStatus {
 interface LogoutURLData {
     url: string;
     saml_request?: string;
+    saml_response?: string;
+    relay_state?: string;
     provider_name?: string;
     binding?: string;
 }
```
Comment (BeryJu) [inline web/src/flow/providers/IFrameLogoutStage.ts]: This shouldn't need to be defined manually, they should come from the API schema

```python


class LogoutURL(PassiveSerializer):

    url = CharField()
    [ ... ]


class IframeLogoutChallenge(Challenge):
    """Challenge for iframe logout"""

    component = CharField(default="ak-provider-iframe-logout")
    logout_urls = ListField(child=LogoutURL(), default=list)


```

File: web/src/flow/providers/IFrameLogoutStage.ts
Comment (BeryJu) [inline web/src/flow/providers/IFrameLogoutStage.ts]:
```

enum LogoutStatusStatus {
    "pending" , "success" , "error",
}

interface LogoutStatus {
    providerName: string;
    status: LogoutStatusStatus;
}
```

mainly for the switch case to complain when it's not exhaustive

File: web/src/flow/stages/autosubmit/AutosubmitStage.ts [hunk 3]
```diff
@@ -25,8 +25,8 @@ export class AutosubmitStage extends BaseStage<
 
     static styles: CSSResult[] = [PFBase, PFLogin, PFForm, PFFormControl, PFButton, PFTitle];
 
-    updated(changed: PropertyValues<this>): void {
-        super.updated(changed);
+    firstUpdated(changed: PropertyValues<this>): void {
+        super.firstUpdated(changed);
 
         if (this.challenge.url !== undefined) {
```
Comment (BeryJu) [inline web/src/flow/stages/autosubmit/AutosubmitStage.ts]:
```suggestion
        if (changed.has("challenge") && this.challenge.url !== undefined) {
```

Comment (BeryJu) [reply web/src/flow/stages/autosubmit/AutosubmitStage.ts]: disclaimer: my solution, not @goauthentik/frontend approved

File: authentik/providers/iframe_logout.py [hunk 4]
```diff
@@ -1,19 +1,31 @@
...
 
+class LogoutURL(PassiveSerializer):
+    """Data for a single logout URL"""
+
+    url = CharField()
+    saml_request = CharField(required=False, allow_null=True)
+    saml_response = CharField(required=False, allow_null=True)
+    relay_state = CharField(required=False, allow_null=True)
+    provider_name = CharField(required=False, allow_null=True)
+    binding = CharField(required=False, allow_null=True)
```
Comment (BeryJu) [inline authentik/providers/iframe_logout.py:18]:
```suggestion
    url = CharField()
    provider_name = CharField()

    # FIXME: separate subclass for SAML for better structure
    saml_binding = CharField(required=False, allow_null=True) # Choice field if possible
    saml_request = CharField(required=False, allow_null=True)
    saml_response = CharField(required=False, allow_null=True)
    saml_relay_state = CharField(required=False, allow_null=True)
```

File: authentik/providers/saml/native_logout.py
Comment (BeryJu) [inline authentik/providers/saml/native_logout.py]:
```suggestion
component = CharField(default="ak-provider-saml-native-logout")

provider_name = CharField()
url = CharField()
binding = CharField() # If possible, choice field

saml_request = CharField(required=False)
saml_response = CharField(required=False)
relay_state = CharField(required=False)

is_complete = BooleanField(default=False)
```

File: authentik/providers/iframe_logout.py [hunk 5]
```diff
@@ -3,29 +3,34 @@
...
     binding = CharField(required=False, allow_null=True)
 
 
+class SAMLLogoutURL(LogoutURL):
+    """SAML-specific logout URL data"""
+
+    saml_request = CharField(required=False, allow_null=True)
+    saml_response = CharField(required=False, allow_null=True)
+    saml_relay_state = CharField(required=False, allow_null=True)
+
```
Comment (BeryJu) [inline authentik/providers/iframe_logout.py]: For the time being we can just do a single class actually

**Review by BeryJu — APPROVED** [review]
