### PR TITLE
outposts/ldap: add more tests

### LINKED ISSUE #6182: LDAP Outpost with 2023.6 is missing posixAccount objectClass
**Describe the bug**

**To Reproduce**

Even though the object class is included in the code it doesn't show in ldapsearch

**Expected behavior**

**Screenshots**

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: [e.g. 2021.8.5]
-   Deployment: [e.g. docker-compose, helm]

**Additional context**

### LINKED ISSUE #6190: LDAP Outpost returns no search results when attributes are filtered
**Describe the bug**
When querying the LDAP outpost, if the search filters attributes then no results are returned, but if the operational attributes are requested with '+' then the results are returned.

**To Reproduce**

* `ldapsearch -H ldap://<ip> -D cn=<user>,ou=users,dc=ldap,dc=goauthentik,dc=io -w password -b 'DC=ldap,DC=goauthentik,DC=io' -b ou=groups,dc=ldap,dc=goauthentik,dc=io -s one 'objectClass=group' dn member`- Fails
* `ldapsearch -H ldap://<ip> -D cn=<user>,ou=users,dc=ldap,dc=goauthentik,dc=io -w password -b 'DC=ldap,DC=goauthentik,DC=io' -b ou=groups,dc=ldap,dc=goauthentik,dc=io -s one 'objectClass=group' '+' dn member` - Works

**Expected behavior**
Results should be returned with filtered attributes as requested.

**Logs**

Failed (`dn member`)
```
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","event":"authenticated from session","level":"info","logger":"authentik.outpost.ldap.binder.session","timestamp":"2023-07-07T23:56:14Z"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"Bind request","level":"info","requestId":"b5ed42a3-5a4e-41f2-b64d-c2de9601b7d0","timestamp":"2023-07-07T23:56:14Z","took-ms":0}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"selecting provider for search request","filter":"(objectClass=group)","level":"trace","provider":"DC=ldap,DC=goauthentik,DC=io","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"routing to default","filter":"(objectClass=group)","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"cn","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"uid","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"sAMAccountName","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"gidNumber","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"ak-superuser","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"objectClass","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"objectClass","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"cn","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"uid","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"sAMAccountName","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"gidNumber","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"ak-superuser","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"ak-superuser","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"objectClass","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"cn","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"uid","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"sAMAccountName","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"gidNumber","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"ak-superuser","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"objectClass","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"cn","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"uid","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"sAMAccountName","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"gidNumber","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"cn","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"uid","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"sAMAccountName","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"gidNumber","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"ak-superuser","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"filtering out field based on LDAP request","filter":"(objectClass=group)","key":"objectClass","level":"trace","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"Search request","filter":"(objectClass=group)","level":"info","requestId":"410627a8-e885-4b69-b205-20397c921dc2","scope":"Single Level","timestamp":"2023-07-07T23:56:14Z","took-ms":1}
{"event":"hello'd","level":"trace","logger":"authentik.outpost.ak-api-controller","loop":"ws-health","timestamp":"2023-07-07T23:56:18Z"}
```

Working (`'+' dn member`)
```
{"event":"hello'd","level":"trace","logger":"authentik.outpost.ak-api-controller","loop":"ws-health","timestamp":"2023-07-07T23:56:58Z"}
{"event":"No session found for user, executing flow","level":"debug","logger":"authentik.outpost.ldap.binder.session","timestamp":"2023-07-07T23:57:00Z"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","component":"ak-stage-identification","event":"Got challenge","flow":"ldap-authentication-flow","level":"debug","requestId":"a9574682-ceb6-4b2e-9b9e-2d12cc0645ff","timestamp":"2023-07-07T23:57:01Z","type":"native"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","component":"xak-flow-redirect","event":"Got response","flow":"ldap-authentication-flow","level":"debug","requestId":"a9574682-ceb6-4b2e-9b9e-2d12cc0645ff","timestamp":"2023-07-07T23:57:02Z","type":"redirect"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"User has access","flow":"ldap-authentication-flow","level":"debug","requestId":"a9574682-ceb6-4b2e-9b9e-2d12cc0645ff","timestamp":"2023-07-07T23:57:02Z"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"User has access","level":"info","requestId":"a9574682-ceb6-4b2e-9b9e-2d12cc0645ff","timestamp":"2023-07-07T23:57:02Z"}
{"allowedGroup":"8eedd232-07e0-44bc-8ff8-676b4ddf0b10","event":"Checking search access","level":"trace","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2023-07-07T23:57:02Z","userGroup":"8eedd232-07e0-44bc-8ff8-676b4ddf0b10"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"Allowed access to search","group":"ldapsearch","level":"info","requestId":"a9574682-ceb6-4b2e-9b9e-2d12cc0645ff","timestamp":"2023-07-07T23:57:02Z"}
{"bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"Bind request","level":"info","requestId":"a9574682-ceb6-4b2e-9b9e-2d12cc0645ff","timestamp":"2023-07-07T23:57:02Z","took-ms":2247}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"selecting provider for search request","filter":"(objectClass=group)","level":"trace","provider":"DC=ldap,DC=goauthentik,DC=io","requestId":"744e6316-d8d4-4c19-a565-dc602531da79","scope":"Single Level","timestamp":"2023-07-07T23:57:02Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"routing to default","filter":"(objectClass=group)","level":"trace","requestId":"744e6316-d8d4-4c19-a565-dc602531da79","scope":"Single Level","timestamp":"2023-07-07T23:57:02Z"}
{"baseDN":"ou=groups,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=pfsense-gw,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.3.1.21","event":"Search request","filter":"(objectClass=group)","level":"info","requestId":"744e6316-d8d4-4c19-a565-dc602531da79","scope":"Single Level","timestamp":"2023-07-07T23:57:02Z","took-ms":0}
{"event":"hello'd","level":"trace","logger":"authentik.outpost.ak-api-controller","loop":"ws-health","timestamp":"2023-07-07T23:57:08Z"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.06.0
-   Deployment: docker-compose

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

Add LDAP Outpost unittests

closes #6190

closes #6190 

closes #6182

### New Features

-   Adds feature which does x, y, and z.

### Breaking Changes

-   Adds breaking change which causes \<issue\>.

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

File: internal/outpost/ldap/search.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ func (ls *LDAPServer) Search(bindDN string, searchReq ldap.SearchRequest, conn n
 			"type":         "search",
 			"app":          selectedApp,
 		}).Observe(float64(span.EndTime.Sub(span.StartTime)))
-		req.Log().WithField("took-ms", span.EndTime.Sub(span.StartTime).Milliseconds()).Info("Search request")
```
Comment (rissson) [inline internal/outpost/ldap/search.go:25]: This might be useful in debugging #6189
