### PR TITLE
outposts: fix flow executor when using subpath

### LINKED ISSUE #13674: Encounter Insufficient Access using LDAP - Authentik
**Describe your question/**
1) Created a LDAP provider. Follow the step in https://docs.goauthentik.io/docs/add-secure-apps/providers/ldap/generic_setup
2) Using LDAP search. However, i encountered error - result: 50 Insufficient access

May I know how to solve the issue?

**Relevant info**
1) Install ldap module in Linux machine.

**Screenshots**

Image

**Logs**

In  ak-outpost-ldap

````
{"event":"Loaded config","level":"debug","path":"inbuilt-default","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Loaded config from environment","level":"debug","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Successfully connected websocket","level":"info","logger":"authentik.outpost.ak-ws","outpost":"c01709d5-901f-4d92-ba23-ebd96a0c36d5","timestamp":"2025-03-26T13:28:46Z"}
{"event":"initialised direct binder","level":"info","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Starting Metrics server","level":"info","listen":"0.0.0.0:9300","logger":"authentik.outpost.metrics","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Starting LDAP SSL server","level":"info","listen":"0.0.0.0:6636","logger":"authentik.outpost.ldap","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Starting LDAP server","level":"info","listen":"0.0.0.0:3389","logger":"authentik.outpost.ldap","timestamp":"2025-03-26T13:28:46Z"}
{"error":"404 Not Found","event":"failed to warm up flow cache","level":"warning","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2025-03-26T13:28:46Z"}
{"event":"Starting authentik outpost","hash":"tagged","level":"info","logger":"authentik.outpost","timestamp":"2025-03-26T13:28:46Z","version":"2025.2.1"}
{"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2025-03-26T13:28:46Z"}
{"error":"404 Not Found","event":"failed to warm up flow cache","level":"warning","logger":"authentik.outpost.ldap.binder.direct","timestamp":"2025-03-26T13:33:46Z"}
{"event":"Update providers","level":"info","logger":"authentik.outpost.ldap","timestamp":"2025-03-26T13:33:46Z"}
{"bindDN":"cn=ldapsearch,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.16.4.50","error":"404 Not Found","event":"failed to execute flow","level":"warning","requestId":"f305ab2b-c5ae-440c-823d-7d8652cec23b","timestamp":"2025-03-26T13:35:19Z"}
{"error":"runtime error: invalid memory address or nil pointer dereference","event":"recover in bind request","level":"error","timestamp":"2025-03-26T13:35:19Z"}
{"bindDN":"cn=ldapsearch,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.16.4.50","event":"Bind request","level":"info","requestId":"f305ab2b-c5ae-440c-823d-7d8652cec23b","timestamp":"2025-03-26T13:35:19Z","took-ms":1}
{"attributes":[],"baseDN":"ou=user,DC=ldap,DC=goauthentik,DC=io","bindDN":"cn=ldapsearch,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.16.4.50","event":"Search request","filter":"(objectClass=user)","level":"info","requestId":"b282f24b-ba0c-4f1e-a34a-05be776a5cf8","scope":"Whole Subtree","timestamp":"2025-03-26T13:35:19Z","took-ms":0}
2025/03/26 13:35:19 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": access denied
{"bindDN":"cn=ldapsearch,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.16.4.93","error":"404 Not Found","event":"failed to execute flow","level":"warning","requestId":"6714cd48-dffe-461c-ae66-e840e9cbd0d0","timestamp":"2025-03-26T13:35:45Z"}
{"error":"runtime error: invalid memory address or nil pointer dereference","event":"recover in bind request","level":"error","timestamp":"2025-03-26T13:35:45Z"}
{"bindDN":"cn=ldapsearch,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.16.4.93","event":"Bind request","level":"info","requestId":"6714cd48-dffe-461c-ae66-e840e9cbd0d0","timestamp":"2025-03-26T13:35:45Z","took-ms":1}
{"attributes":[],"baseDN":"ou=user,DC=ldap,DC=goauthentik,DC=io","bindDN":"cn=ldapsearch,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"172.16.4.93","event":"Search request","filter":"(objectClass=user)","level":"info","requestId":"63b5d67d-5188-4bfc-ac06-ae872ca45ca2","scope":"Whole Subtree","timestamp":"2025-03-26T13:35:45Z","took-ms":0}
2025/03/26 13:35:45 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": access denied
````

**Version and Deployment (please complete the following information):**
Authentik : 2025.2.1
Deployment : Kubernetes

-   authentik version: [e.g. 2025.2.0]
-   Deployment: [e.g. docker-compose, helm]

### PR DESCRIPTION
**Pull request by ikob**
## Details
The API URL now includes the web path. Outposts can coexist with authentik deployed behind a reverse proxy under a web path. This PR fix outposts/radius as well.

Note: The AUTHENTIK_HOST environment variable should include the web path, e.g., `http://authentik.io:9000/authentik/`.

closes #13674 (Address comment raised by @najose)

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make docs`)

### CODE REVIEW

File: internal/outpost/flow/executor.go [hunk 1]
```diff
@@ -82,6 +82,11 @@ func NewFlowExecutor(ctx context.Context, flowSlug string, refConfig *api.Config
 	config := api.NewConfiguration()
 	config.Host = refConfig.Host
 	config.Scheme = refConfig.Scheme
+	config.Servers = api.ServerConfigurations{
+		{
+			URL: (*refConfig).Servers[0].URL,
```
Comment (BeryJu) [inline internal/outpost/flow/executor.go]:
```suggestion
			URL: refConfig.Servers[0].URL,
```

Comment (ikob) [reply internal/outpost/flow/executor.go]: @BeryJu,
Thanks, I am less familiar with Go than with C.

**Review by BeryJu — APPROVED** [review]
