### PR TITLE
web/admin: providers/rac: improve host field hint

### LINKED ISSUE #16424: Add port to hints of "Update Endpoint" dialog
**Describe the bug**

There is a field "HOST" in the "UPDATE ENDPOINT" dialog:

It's hint said: 

> Hostname/IP to connect to.

It was not immediately obvious, but the same field is also used for PORT.

Please add information about port to the hint. Something like:

> Hostname/IP and optionally port to connect to.

**Screenshots**

Image

**Version and Deployment (please complete the following information):**

-   authentik version: 2025.8.1
-   Deployment: helm

### PR DESCRIPTION
**Pull request by dewi-tik**
## Details

Adds mention of configuring ports to the host field in RAC endpoint setup

Closes #16424

---

## Checklist

-   [x] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)

### CODE REVIEW

File: web/src/admin/providers/rac/EndpointForm.ts [hunk 1]
```diff
@@ -91,7 +91,9 @@ export class EndpointForm extends ModelForm<Endpoint, string> {
                     class="pf-c-form-control"
                     required
                 />
-                <p class="pf-c-form__helper-text">${msg("Hostname/IP to connect to.")}</p>
+                <p class="pf-c-form__helper-text">
+                    ${msg("Hostname/IP to connect to. Optionally specify the port.")}
```
Comment (dominic-r) [inline web/src/admin/providers/rac/EndpointForm.ts:95]: In what cases would not need to specify the port

Comment (dewi-tik) [reply web/src/admin/providers/rac/EndpointForm.ts:95]: If the endpoint isn't using the default port for RDP, SSH or VNC

**Review by BeryJu — APPROVED** [review]
