### PR TITLE
web: providers/rac: Fix wizard confirmation

### LINKED ISSUE #15993: RAC Wizard final step missing provider info
On the last step of the wizard when attempting to create a RAC appli/provider pair, notice the provider configuration missing:

Image

There has to be at least one thing to mention such as the connection expiry, otherwise, the section should be hidden

### PR DESCRIPTION
**Pull request by dominic-r**
Signed-off-by: Dominic R <dominic@sdko.org>
Closes: https://github.com/goauthentik/authentik/issues/15993

## Details

REPLACE ME

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make docs`)

### CODE REVIEW

**Comment by dominic-r** [comment]
I've never done this before, but I'd assume this should look right

File: web/src/admin/applications/wizard/steps/SubmitStepOverviewRenderers.ts [hunk 1]
```diff
@@ -50,7 +50,16 @@ function renderRadiusOverview(rawProvider: OneOfProvider) {
 }
 
 function renderRACOverview(rawProvider: OneOfProvider) {
-    const _provider = rawProvider as RACProvider;
+    const provider = rawProvider as RACProvider;
+    return renderSummary("RAC", provider.name, [
+        [msg("Connection expiry"), provider.connectionExpiry ?? "-"],
+        [
+            msg("Property mappings"),
+            Array.isArray(provider.propertyMappings) && provider.propertyMappings.length > 0
```
Comment (GirlBossRush) [inline web/src/admin/applications/wizard/steps/SubmitStepOverviewRenderers.ts]:
```suggestion
            Array.isArray(provider.propertyMappings) && provider.propertyMappings.length
```

**Review by GirlBossRush — APPROVED** [review]
