### PR TITLE
outpost/proxyv2: more tests, fix pg password with spaces, and existing session on restart

### LINKED ISSUE #18130: Proxy Outpost Basic Auth 2025.10.x Breaks after Outpost Restart
**Describe the bug**
As described in [this other](https://github.com/goauthentik/authentik/issues/17779) (now resolved) bug, basic auth through the proxy provider wasn't working on 2025.10.0. The solution (included in 2025.10.1) does work on the embedded outpost, but I can't seem to get *non*-embedded outposts running 2025.10.1 to send basic auth credentials *after they restart* and the sessions are reset.

I made an issue [here](https://github.com/goauthentik/authentik/issues/18098) about session storage with the outpost proxy that's worth noting. There I learned that currently, because the session storage is in memory & can't be stored elsewhere, when my single outpost pod restarts, I lose all my sessions stored by the outpost.

When this happens, every application that relied on basic auth credential sending from the provider, now prompts me for basic auth.

I can get the basic auth to work again as intended when I fully clear my browser's cache and log back into Authentik. Simply logging out & back into Authentik does not fix it - I need to clear the cookies.

**To Reproduce**

1. Add a proxy outpost (I made mine manually on k8s)
2. Add a proxy provider w/ basic auth credentials
3. Assign the application to your external proxy outpost
4. Log into the application using the outpost
5. Kill the outpost container, clearing out its stored sessions. Wait for new outpost pod to start.
6. Refresh the page of the application

**Expected behavior**
The application shouldn't prompt me for basic auth after an outpost restart

**Logs**
Startup logs are normal after restart

When refreshing the application page after an outpost restart, logs like this one occur.
```bash
{"error":"failed to get session: open /dev/shm/session_TH4LDU4USSDPDED2TEYUG6OV5BHLG3TFBRPB45M2WNFTIQAVI3XQ: no such file or directory","event":"failed to create state","level":"warning","logger":"authentik.outpost.proxyv2.application","name":"Provider for Radarr","timestamp":"2025-11-13T20:10:24Z"}
```
I'd expect that for the first request, but it doesn't seem to be recovering after, it just logs the same thing for every request I send.

**Version and Deployment (please complete the following information):**

-   authentik version: 2025.10.1
-   Deployment: helm

### PR DESCRIPTION
**Pull request by dominic-r**
And modify / add some more tests and a bit of refactoring

Closes: https://github.com/goauthentik/authentik/issues/18175

## Details

REPLACE ME

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make docs`)

### CODE REVIEW

File: internal/outpost/proxyv2/postgresstore/postgresstore.go [hunk 1]
```diff
@@ -49,60 +53,121 @@ func (ProxySession) TableName() string {
...
+					return nil, fmt.Errorf("failed to load SSL client certificate: %w", err)
+				}
+				tlsConfig.Certificates = []tls.Certificate{cert}
+			}
+
+			// Set verification mode
+			switch cfg.SSLMode {
+			case "require":
+				// Verify the server certificate (secure by default)
+				tlsConfig.InsecureSkipVerify = false
```
Comment (JohnTheNerd) [inline internal/outpost/proxyv2/postgresstore/postgresstore.go]: I think this change, as-is, is a breaking change that does not conform to the Postgres or Authentik documentation. If SSL mode is set to require, the documented behavior is to _not_ check certificate validity:

- https://www.postgresql.org/docs/current/libpq-ssl.html

- https://docs.goauthentik.io/install-config/configuration/ (currently not viewable due to the ongoing CloudFlare outage)

This change instead makes "require" equivalent to "verify-ca". If this is intended to be the case, it should be documented as a breaking change.

Comment (dominic-r) [reply internal/outpost/proxyv2/postgresstore/postgresstore.go]: Yea, I need to change that, Good catch.

Comment (dominic-r) [reply internal/outpost/proxyv2/postgresstore/postgresstore.go]: I've reverted the CodeQL alert

**Review by BeryJu — APPROVED** [review]
