### PR TITLE
stages/authenticator_static: set max token length to 100 chars

### LINKED ISSUE #19158: Static Tokens longer than 16 chars result in UI glitch and application+database error
### Describe the bug

In the UI, the tokens are "glitched" and are overlapping, making it non-readable:
Image

When continuing, it results in vague server error:
Image

In logs specific database error `DataError('value too long for type character varying(16)` occurs.

### How to reproduce

1. Go to stages
2. Edit static tokens stage
3. Increase it beyond 16
4. Configure static tokens, e.g. during login flow with enforced MFA.
    For example:
    Image

### Expected behavior

No error to occur when being configurable / not being configurable.

### Screenshots

_No response_

### Additional context

_No response_

### Deployment Method

Docker

### Version

2025.10.3

### Relevant log output

```shell
server-1  | {"auth_via": "unauthenticated", "domain_url": "authentik.company", "event": "DataError('value too long for type character varying(16)')", "flow_slug": "pk-authentication", "host": "authentik.company", "level": "warning", "logger": "authentik.flows.views.executor", "pid": 34730, "request_id": "9ff7fb9bde7b460e96ef475ad5ba36c0", "schema_name": "public", "timestamp": "2026-01-02T13:27:15.092827"}
```

### PR DESCRIPTION
**Pull request by dominic-r**
Sets maximum static token length to 100 cause of some math Gergo did. Also adds a validator and gives the max value to the user in the ui. slightly improves/tweaks the UI to wrap on long tokens and render one per line.

ui snapshots:

50:
image

16:
image

Closes: https://github.com/goauthentik/authentik/issues/19158

### CODE REVIEW

File: web/src/admin/stages/authenticator_static/AuthenticatorStaticStageForm.ts [hunk 1]
```diff
@@ -94,14 +94,16 @@ export class AuthenticatorStaticStageForm extends BaseStageForm<AuthenticatorSta
...
                             value="${this.instance?.tokenLength ?? 12}"
+                            min="1"
+                            max="16"
                             class="pf-c-form-control"
                             required
                         />
                         <p class="pf-c-form__helper-text">
                             ${msg(
-                                "The length of the individual generated tokens. Can be increased to improve security.",
+                                "The length of the individual generated tokens. Can be set to a maximum of 16 characters.",
```
Comment (kensternberg-authentik) [inline web/src/admin/stages/authenticator_static/AuthenticatorStaticStageForm.ts]: Kinda long.  

> The length of the individual generated tokens. Maximum of 16 characters.

**Review by kensternberg-authentik — APPROVED** [review]

**Review by gergosimonyi — COMMENTED** [review]
Recommendation: instead, the database should accept tokens up to length `n` where `n` is way greater than 16 and, let's say, at least 43. With the current `[0-9a-zA-Z]` alphabet that would give log_2(62^43)≈256 bits of entropy for anyone who wants that.

**Review by gergosimonyi — APPROVED** [review]
