### PR TITLE
web/user: fix broken search on application library

### LINKED ISSUE #5171: UX: add an actionable button to "No Applications" page
For new installations that do not yet have any applications created, users will see a "No Applications Available" message on the Applications page of the user interface. But it is not immediately obvious how to fix the problem... can be frustrating.

Let's add a button there that takes them to the page in the UI to create an app, or to the docs on how to...

Screenshot with proposal is attached. Also, see how the Policy Binding page has a CTA button; let's do similar.

Screenshot 2023-03-09 at 8 29 59 AM

### PR DESCRIPTION
**Pull request by kensternberg-authentik**
This is *mortifying*.  I didn't test this well enough, and apparently broke it again once I'd tested it.  This patch restores the original behavior ("no match" means "just show everything"), and fixes a small bit of semantic lint -- the "search" feature should not be assigning meaning to what it finds; it's enough to pass back the prioritized list to whatever client wanted it, and let the client decide what to do with it.

## Details

-   **Does this resolve an issue?**
    
Resolves #5171

## Changes

Fixes the search feature so that the data being passed back and forth correspond to the design.

-   [X] Local tests pass (`ak test authentik/`)
-   [X] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [X] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [X] The code has been formatted (`make web`)
-   [X] The translation files have been updated (`make i18n-extract`)

### CODE REVIEW

File: web/src/user/LibraryPage/LibraryPageImpl.ts [hunk 1]
```diff
@@ -125,7 +130,7 @@ export class LibraryPage extends AKElement {
     }
 
     renderSearch() {
-        return html`<ak-library-list-search .apps="{this.apps.results}"></ak-library-list-search>`;
+        return html`<ak-library-list-search .apps=${this.apps.results}></ak-library-list-search>`;
```
Comment (kensternberg-authentik) [inline web/src/user/LibraryPage/LibraryPageImpl.ts:133]: This was the real issue; everything else is just dealing with errors to the console when the field is cleared (when there is no `app[0]`).  I got this to work, then moved it here and effed-up my argument call.  Massive apologies.

**Review by BeryJu — APPROVED** [review]
