### PR TITLE
web: Fix issues surrounding wizard step behavior.

### LINKED ISSUE #12691: Clicking "Back" in some Admin interface modals breaks "Next" button
**Describe the bug**
Some pages of the Admin interface such as the Policies page allow users to open a modal to select a more detailed choice (Policies -> Reputation Policy). When the user attempts to move forward, everything works fine. However, when the user clicks the "Back" button, it is impossible for them to click "Next" again without invalidating their selection (Closing the modal or switching to another option then switching back). 

**To Reproduce**

1. From the authentik Admin interface, navigate to Customization -> Policies and click "Create"
2. Select a policy of your choice such as "Reputation Policy" and click "Next"
3. Click the "Back button" & See screenshot for described effect

**Expected behavior**
The user is able to click the "Next" button without needing to select one of the resolution steps in the "Describe the bug" section.

**Screenshots**
image

**Logs**
No logs  in browser console or in authentik

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.12.2
-   Deployment: docker compose

**Additional context**

### PR DESCRIPTION
**Pull request by GirlBossRush**
## Details

Hi team! 👋

As reported in #12691, this PR resolves a few stateful situations which may arise when opening and closing wizard pages, such as...

- Opening a wizard, progressing a step, then returning to a prior step.
- Opening a wizard, interacting with the form, then closing it. 

This PR also includes some minor bits of polish to better my understanding of idiomatic lit-html. Please let me know if my modifications are aligned current best practices.

Thank you for your guidance!

Closes #12691

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

File: web/src/admin/policies/PolicyWizard.ts [hunk 1]
```diff
@@ -52,6 +52,21 @@ export class PolicyWizard extends AKElement {
         });
     }
 
+    selectListener = ({ detail }: CustomEvent<TypeCreate>) => {
```
Comment (GirlBossRush) [inline web/src/admin/policies/PolicyWizard.ts:55]: Brought out from inline implementation for readability.

File: web/src/elements/wizard/TypeCreateWizardPage.ts [hunk 2]
```diff
@@ -160,6 +181,8 @@ export class TypeCreateWizardPage extends WithLicenseSummary(WizardPage) {
                 return this.renderGrid();
             case TypeCreateWizardPageLayouts.list:
                 return this.renderList();
+            default:
```
Comment (GirlBossRush) [inline web/src/elements/wizard/TypeCreateWizardPage.ts:184]: Ensures runtime type safety with exhaustive default.

File: web/src/elements/wizard/Wizard.ts [hunk 3]
```diff
@@ -20,91 +21,149 @@ export const ApplyActionsSlot = "apply-actions";
...
+
+        for (const step of this._steps) {
+            const existingStepElement = this.getStepElementByName(step);
+
+            if (existingStepElement) continue;
+
+            const stepElement = document.createElement(step);
+
+            stepElement.slot = step;
+            stepElement.dataset["wizardmanaged"] = "true";
```
Comment (GirlBossRush) [inline web/src/elements/wizard/Wizard.ts:115]: Not sure if this is still being used.

File: web/src/elements/wizard/Wizard.ts [hunk 4]
```diff
@@ -20,91 +21,149 @@ export const ApplyActionsSlot = "apply-actions";
...
     _initialSteps: string[] = [];
 
-    @property({ attribute: false })
-    actions: WizardAction[] = [];
-
     @state()
-    _currentStep?: WizardPage;
+    _activeStep?: WizardPage;
 
-    set currentStep(value: WizardPage | undefined) {
```
Comment (GirlBossRush) [inline web/src/elements/wizard/Wizard.ts:82]: Preferred use of `active` over `current` to emphasize the state of the step, rather than its order in the array. Also to differentiate between `ref.current`.

File: web/src/elements/wizard/Wizard.ts [hunk 5]
```diff
@@ -20,91 +21,149 @@ export const ApplyActionsSlot = "apply-actions";
...
-    };
+    getStepElementByIndex(stepIndex: number): WizardPage | null {
+        const stepName = this._steps[stepIndex];
 
-    @property({ attribute: false })
-    state: { [key: string]: unknown } = {};
+        return this.querySelector<WizardPage>(`[slot=${stepName}]`);
+    }
+
+    getStepElementByName(stepName: string): WizardPage | null {
```
Comment (GirlBossRush) [inline web/src/elements/wizard/Wizard.ts:153]: I suspect these could be ref'd at some point but if they're like React refs, dealing with live element arrays is tricky. Another idea was to use a Map, but I could see it getting out of sync with the DOM.

File: web/src/elements/wizard/Wizard.ts [hunk 6]
```diff
@@ -114,7 +173,9 @@ export class Wizard extends ModalButton {
     }
 
     /**
-     * Add action at the end of the list
+     * Add action at the end of the list.
+     *
+     * @todo: Is this used?
```
Comment (GirlBossRush) [inline web/src/elements/wizard/Wizard.ts:178]: Vestigial or part of a new system?

File: web/src/elements/wizard/Wizard.ts [hunk 7]
```diff
@@ -123,31 +184,72 @@ export class Wizard extends ModalButton {
...
                           aria-label="${msg("Close")}"
-                          @click=${() => {
-                              this.reset();
-                          }}
+                          @click=${this.reset}
                       >
                           <i class="fas fa-times" aria-hidden="true"></i>
                       </button>`
-                    : html``}
+                    : nothing}
```
Comment (GirlBossRush) [inline web/src/elements/wizard/Wizard.ts:252]: AFAIK both `html`\`` and `nothing` appear interchangeable. Should we settle on one?

File: web/src/elements/wizard/Wizard.ts [hunk 8]
```diff
@@ -123,31 +184,72 @@ export class Wizard extends ModalButton {
...
+        this.open = false;
+
+        this.querySelectorAll("[data-wizardmanaged=true]").forEach((el) => {
+            el.remove();
+        });
+
+        for (const step of this.steps) {
+            const stepElement = this.getStepElementByName(step);
+
+            stepElement?.reset?.();
```
Comment (GirlBossRush) [inline web/src/elements/wizard/Wizard.ts:200]: I contemplated performing a `querySelectorAll('form')` but suspected that it would go against the Shadow DOM encapsulation. Given that each step element acts like a form element, it felt appropriate to give them a `reset` method.

**Review by kensternberg-authentik — APPROVED** [review]
I approve, although the Wizards (both the simple one and the more complicated one in ak-wizard) are bad examples of "screaming" architecture; it's hard to know what each piece does in isolation.  That's partially my fault, though.
