### PR TITLE
web/admin: fix html error on oauth2 provider page

### LINKED ISSUE #7375: Create or edit Oauth2 provider page - unable to tick "include claims in ID token" due to malformed HTML?
**Describe the bug**
I am unable to enable the "include claims in ID token" on either a new or existing provider. It looks like there is a missing HTML anchor or something (not a HTML expert - sorry if I am using the wrong terminoloyg) on the page, and when I enable the switch and update/save, when I go back in to check it is still disabled.

**To Reproduce**

1. Go to 'Admin Interface/Applications/Providers/' and choose to either create new or edit eisting provider
2. Expand 'Advanced protocol settings'
3. Malformed HTML can be seen.
4. Click switch to turn on "include claims in ID token"
5. Click update
6. Go back in to provider and switch is still turned off.

**Expected behavior**
Not see the malformed HTML and to be able to enable the switch to "include claims in ID token".

**Screenshots**
image

**Logs**
Not relevant - no errors or warnings. 
Entry in log when I update a claim 
```
INF action=model_updated auth_via=session client_ip=<redacted> context={"geo":{"city":"<redacted>},"http_request":{"args":{},"method":"PUT","path":"/api/v3/providers/oauth2/11/"},"model":{"app":"authentik_providers_oauth2","model_name":"oauth2provider","name":"App","pk":11}} event=Created Event host=<redacted> logger=authentik.events.models pid=22 request_id=<redacted> timestamp=2023-10-29T23:50:41.809732 user={"email":"<redacted>","pk":7,"username":"<redacted>"}
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.2
-   Deployment: docker-compose

**Additional context**

### PR DESCRIPTION
**Pull request by kensternberg-authentik**
## Details

Extra `>` symbol screwed up the reading of the rest of the component.  Unfortunately, too many fields in an input are optional, so it was easy for this bug to bypass any checks by the validators.  I should have caught it myself, though.

closes #7375 
---

## Checklist

-   [x] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [x] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)
-   [x] The translation files have been updated (`make i18n-extract`)

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

### CODE REVIEW

File: web/src/admin/providers/oauth2/OAuth2ProviderForm.ts [hunk 1]
```diff
@@ -334,13 +334,14 @@ export class OAuth2ProviderFormPage extends ModelForm<OAuth2Provider, number> {
                         )}
                     >
                     </ak-radio-input>
-                    <ak-switch-input name="includeClaimsInIdToken">
```
Comment (kensternberg-authentik) [inline web/src/admin/providers/oauth2/OAuth2ProviderForm.ts:337]: It's that extra `>` at the end of this line that screwed everything up. It isn't so much "malformed HTML" as "insufficiently specified HTML."

**Review by BeryJu — APPROVED** [review]
