### PR TITLE
tests/e2e: add test for authentication flow in compatibility mode

### LINKED ISSUE #13839: Can't View Proxy Provider Setup tabs - Allow-Snippet-Annotations Error
**Describe the bug**

**To Reproduce**

1. Go to Providers
2. Click on any Provider
3. On the Overview Tab scroll down to the invidual Setup tabs for each Proxy type

**Expected behavior**
I expect to see various configurations for each Proxy Type (Nginx Proxy manager, Traefik, Caddy, etc)

**Screenshots**

Image

Browser Console logs:

```
authentik/ws: closed ws connection 
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
[chunk-TO7UQKFF.js:7905:234](https://auth.ecorp.rip/static/dist/admin/chunk-TO7UQKFF.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://authentik.error-reporting.a7k.io/api/4504163677503489/envelope/?sentry_key=151ba72610234c4c97c5bcff4e1cffd8&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.33.1. (Reason: CORS request did not succeed). Status code: (null).

```plaintext
authentik/ws: closed ws connection
close { target: WebSocket, isTrusted: true, wasClean: true, code: 1001, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
[chunk-TO7UQKFF.js:7905:234](https://auth.xxxx.xxx/static/dist/admin/chunk-TO7UQKFF.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://authentik.error-reporting.a7k.io/api/4504163677503489/envelope/?sentry_key=151ba72610234c4c97c5bcff4e1cffd8&sentry_version=7&sentry_client=sentry.javascript.browser%2F8.33.1. (Reason: CORS request did not succeed). Status code: (null).

authentik(early): version 2025.2.4, apiBase https://auth.xxxx.xxx/api/v3 [config.ts:89:8](https://auth.xxxx.xxx/static/src/common/api/config.ts)
authentik/interface[ak-loading]: Enabling theme dark [Interface.ts:63:16](https://auth.xxxx.xxx/static/src/elements/Interface/Interface.ts)
authentik(early): version 2025.2.4, apiBase https://auth.xxxx.xxx/api/v3 [config.ts:89:8](https://auth.xxxx.xxx/static/src/common/api/config.ts)
authentik/interface[ak-interface-admin]: Enabling theme dark [Interface.ts:63:16](https://auth.xxxx.xxx/static/src/elements/Interface/Interface.ts)
authentik/locale: Setting Locale to English (en) [ak-locale-context.ts:80:20](https://auth.xxxx.xxx/static/src/elements/ak-locale-context/ak-locale-context.ts)
authentik/router: found match
Object { route: {…}, arguments: {…}, fullUrl: "/core/providers/5" }
[RouterOutlet.ts:98:24](https://auth.xxxx.xxx/static/src/elements/router/RouterOutlet.ts)
authentik/config: Sentry enabled. [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/ws: connected to wss://auth.xxxx.xxx/ws/client/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/root/config/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/enterprise/license/summary/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/core/brands/current/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/admin/version/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/core/users/me/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/events/notifications/?ordering=-created&page_size=1&seen=false&user=6 [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/events/notifications/?ordering=-created&seen=false&user=6 [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/providers/all/5/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/providers/proxy/5/ [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/rbac/permissions/assigned_by_roles/?model=authentik_providers_proxy.proxyprovider&object_pk=5&page=1&page_size=20 [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/events/events/?action=model_&context_model_app=authentik_providers_proxy&context_model_pk=5&ordering=-created&page=1&page_size=20 [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/rbac/permissions/assigned_by_users/?model=authentik_providers_proxy.proxyprovider&object_pk=5&page=1&page_size=20 [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
authentik/api[authentik-default]: 200 GET https://auth.xxxx.xxx/api/v3/rbac/permissions/?content_type__app_label=authentik_providers_proxy&content_type__model=proxyprovider&ordering=codename 2 [console.ts:40:19](https://auth.xxxx.xxx/static/node_modules/@sentry/utils/src/instrument/console.ts)
```
```

-   authentik version:  2025.2.4
-   Docker in Unraid

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

This was previously not tested in e2e

Closes #13839

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Review by kensternberg-authentik — APPROVED** [review]
Small and straightforward.

**Review by GirlBossRush — APPROVED** [review]

**Review by GirlBossRush — APPROVED** [review]

File: web/.storybook/manager.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
+/**
+ * @file Storybook manager configuration.
+ *
+ * @import { ThemeVarsPartial } from "storybook/internal/theming";
+ */
+import { createUIThemeEffect, resolveUITheme } from "@goauthentik/web/common/theme.ts";
```
Comment (GirlBossRush) [inline web/.storybook/manager.js:6]: Using `.ts` seems to clue Storybook's bundler into consistently resolving submodules.

File: web/.storybook/preview-head.html [hunk 2]
```diff
@@ -1,5 +1,3 @@
-<link rel="stylesheet" href="@patternfly/patternfly/patternfly-base.css" />
-<link rel="stylesheet" href="@goauthentik/common/styles/authentik.css" />
```
Comment (GirlBossRush) [inline web/.storybook/preview-head.html:2]: Handled the `preview.js` init much like we do in the web component interfaces

File: web/src/admin/AdminInterface/index.entrypoint.ts [hunk 3]
```diff
@@ -81,50 +81,48 @@ export class AdminInterface extends WithLicenseSummary(AuthenticatedInterface) {
...
                 .pf-c-page {
-                    background-color: var(--pf-c-page--BackgroundColor) !important;
-                }
-
-                :host([theme="dark"]) {
-                    /* Global page background colour */
-                    .pf-c-page {
-                        --pf-c-page--BackgroundColor: var(--ak-dark-background);
-                    }
+                    --pf-c-page--BackgroundColor: var(--ak-dark-background);
```
Comment (GirlBossRush) [inline web/src/admin/AdminInterface/index.entrypoint.ts:109]: Fixes odd styling when using ShadyDOM

File: web/src/common/styles/authentik.css [hunk 4]
```diff
@@ -1,5 +1,9 @@
 /* #region Global */
 
+.__AK_BASE_STYLES__ {
+    --__AK_BASE_STYLES__: 1;
+}
+
```
Comment (GirlBossRush) [inline web/src/common/styles/authentik.css:6]: Added to better debug constructed stylesheets via [`inspectStyleSheetTree`](https://github.com/goauthentik/authentik/blob/ae2af6e58e4f7f4255f804c18188b50f80c5018b/web/src/common/stylesheets.ts#L176)

Screenshot 2025-05-09 at 02 15 29

File: web/src/common/styles/theme-dark.css [hunk 5]
```diff
@@ -256,8 +257,13 @@ input[type="date"]::-webkit-calendar-picker-indicator {
...
 
-.pf-c-button.pf-m-plain:hover {
-    color: var(--ak-dark-foreground);
+.pf-c-button.pf-m-plain {
+    --pf-c-button--m-plain--focus--Color: var(--pf-global--Color--200);
+    --pf-c-button--m-plain--hover--Color: var(--ak-dark-foreground);
+
+    &:focus:hover {
+        color: var(--pf-c-button--m-plain--hover--Color);
+    }
```
Comment (GirlBossRush) [inline web/src/common/styles/theme-dark.css:266]: Fixes issue revealed when testing ShadyDOM. Toggling the navigation sidebar now consistently retains the hover-state color.

File: web/src/common/theme.ts [hunk 6]
```diff
@@ -1,10 +1,47 @@
...
 
+//#region Stylesheet Exports
+
+/**
+ * A global style sheet for the Patternfly base styles.
+ *
+ * @remarks
+ *
+ * While a component *may* import its own instance of the PFBase style sheet,
+ * this instance ensures referential identity.
```
Comment (GirlBossRush) [inline web/src/common/theme.ts:25]: This is most relevant when applying global styles to the document (via Storybook), or to  a web component (via Interface)

File: web/src/elements/Base.ts [hunk 7]
```diff
@@ -1,139 +1,152 @@
...
+        this.#themeAbortController?.abort();
+
+        this.#styleRoot = nextStyleRoot;
+
+        if (!nextStyleRoot) return;
+
+        if (this.#customCSSStyleSheet) {
+            setAdoptedStyleSheets(nextStyleRoot, (currentStyleSheets) => {
+                return [...currentStyleSheets, this.#customCSSStyleSheet!];
+            });
```
Comment (GirlBossRush) [inline web/src/elements/Base.ts:132]: I suspect this touches a spec ambiguity and might come up in the future. Replacing a style root's `adoptedStyleSheets` will not take effect until the next repaint.

Appending to `adoptedStyleSheets` in the same frame would mean spreading out the previous entries, which would not yet be available in the array since they haven't yet mounted. We can't easily cache the previous entries since the style root may be a ShadyDOM.

That leaves us with a `requestAnimationFrame` to sequence the adoption + a visibility toggling to avoid a flash of styles between renders.

Comment (GirlBossRush) [reply web/src/elements/Base.ts:132]: @BeryJu @kensternberg-authentik

File: web/src/elements/Base.ts [hunk 8]
```diff
@@ -1,139 +1,152 @@
...
-        if (this.#preferredColorScheme === "dark") {
-            this.#dispatchTheme(UiThemeEnum.Dark);
-        } else if (this.#preferredColorScheme === "auto") {
-            createUIThemeEffect(this.#dispatchTheme, {
+        if (this.preferredColorScheme === "dark") {
+            applyUITheme(nextStyleRoot, UiThemeEnum.Dark);
+
+            this.activeTheme = UiThemeEnum.Dark;
+        } else if (this.preferredColorScheme === "auto") {
+            createUIThemeEffect((nextUITheme) => applyUITheme(nextStyleRoot, nextUITheme), {
```
Comment (GirlBossRush) [inline web/src/elements/Base.ts:142]: Small revision to split off the logic of applying a theme into a function that Storybook and WebDriver's test runner can use.

File: web/src/elements/ak-mdx/ak-mdx.tsx [hunk 9]
```diff
@@ -67,80 +70,92 @@ export class AKMDX extends AKElement {
...
-                    --pf-global--link--Color: var(--pf-global--link--Color--light);
-                    --pf-global--link--Color--hover: var(--pf-global--link--Color--light--hover);
-                    --pf-global--link--Color--visited: var(--pf-global--link--Color);
+    static styles = [
+        PFBase,
+        PFList,
+        PFTable,
+        PFContent,
+        OneDark,
+        css`
```
Comment (GirlBossRush) [inline web/src/elements/ak-mdx/ak-mdx.tsx:79]: Fixes #13839

File: web/src/elements/Base.ts (hunk 7 above)
Comment (BeryJu) [reply web/src/elements/Base.ts]: ideally theming would just be a CSS file with a bunch of variables to set colours, but in PF4 there are still cases where colours are set statically/can't be overridden exactly enough

File: web/src/common/styles/authentik.css (hunk 4 above)
Comment (BeryJu) [reply web/src/common/styles/authentik.css:6]: Should probably add a comment to the code why that's there
