### PR TITLE
web: fix Brand CSS not applied to nested Shadow DOM components

### LINKED ISSUE #19556: Custom CSS under Branding settings do not apply after upgrading from 2025.10 to 2025.12
### Describe the bug

After upgrading my docker compose to 2025.12, the custom CSS under Branding settings is not applied any more

As an example, I'm trying to change the background color of the div below by adding the following CSS

.pf-c-login__main-header.pf-c-brand
{
  background-color: rgb(3 3 3 / 20%) !important;
}

`<div class="pf-c-login__main-header pf-c-brand" part="branding">
                    authentik Logo
                </div>`

Image

However, that doesn't change the color. Also all the other customization that I have done, are not working.

### How to reproduce

1. Go to System
2. Go to Brands
3. Edit a Brand
4. Under Branding settings > Custom CSS, apply any CSS that should change a color of any element

### Expected behavior

The CSS should apply

### Screenshots

_No response_

### Additional context

_No response_

### Deployment Method

Docker

### Version

2025.12.1

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Mmx233**
## Details

After PR #17444, Brand CSS was only applied when ThemeChangeEvent fired. Components created after the initial event never received the custom styles.

This fix immediately applies Brand CSS when a style root is set, ensuring all nested Shadow DOM components (like flow stages) receive brand styling regardless of when they are created.

Made and tested with a test image based on the `version/2025.12.2` tag: `mmx233/authentik:2025.12.2-fix-brand-css`

Fixes #19556

---

## Checklist

-   [x] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make docs`)

### CODE REVIEW

File: web/src/elements/Base.ts [hunk 1]
```diff
@@ -177,6 +177,13 @@ export class AKElement extends LitElement implements AKElementProps {
                 signal: this.#themeAbortController.signal,
             },
         );
+
+        // Immediately apply Brand CSS to the style root.
+        // This ensures nested Shadow DOM components created after the initial
+        // ThemeChangeEvent still receive the custom brand styles.
```
Comment (GirlBossRush) [inline web/src/elements/Base.ts]:
```suggestion

```

**Review by GirlBossRush — APPROVED** [review]
