### PR TITLE
outposts/ldap: Handle comma-separated attributes in LDAP search requests

### LINKED ISSUE #13539: Jira LDAP Queries are not working due to the Attributes format
When configuring Kira to synchronize with Authentik LDAP Outpost, the queries fail. After investigation, it seems that it is due to the way Jira requests the Attributes to be provided by the LDAP server.

LDAP Outpost logs:

> {"baseDN":"ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=ldap-user,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.229.46.174","event":"selecting provider for search request","filter":"(memberOf=cn=customer,ou=groups,dc=ldap,dc=goauthentik,dc=io)","level":"trace","provider":"DC=ldap,DC=goauthentik,DC=io","requestId":"3a9b2790-93ce-4cb9-a359-9f351354c3bb","scope":"Whole Subtree","timestamp":"2025-03-14T21:55:33Z"}
> {"baseDN":"ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=ldap-user,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.229.46.174","event":"routing to default","filter":"(memberOf=cn=customer,ou=groups,dc=ldap,dc=goauthentik,dc=io)","level":"trace","requestId":"3a9b2790-93ce-4cb9-a359-9f351354c3bb","scope":"Whole Subtree","timestamp":"2025-03-14T21:55:33Z"}
> {"attributes":["uid","cn","sn"],"baseDN":"ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=ldap-user,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.229.46.174","event":"Search request","filter":"(memberOf=cn=customer,ou=groups,dc=ldap,dc=goauthentik,dc=io)","level":"info","requestId":"3a9b2790-93ce-4cb9-a359-9f351354c3bb","scope":"Whole Subtree","timestamp":"2025-03-14T21:55:33Z","took-ms":403}
> 2025/03/14 21:55:33 handleSearchRequest error LDAP Result Code 1 "Operations Error": LDAP Result Code 1 "Operations Error": Bad search request

The server sent a HTTP 200, so no issue. Server logs for the above query:

> {"auth_via": "api_token", "domain_url": "10.229.46.151", "event": "/api/v3/core/users/?groups_by_name=customer&include_groups=true&page=1&page_size=100", "host": "10.229.46.151:9000", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 1242674, "remote": "172.19.0.1", "request_id": "09376c93e66e4b9aaea4be8bfc633d35", "runtime": 345, "schema_name": "public", "scheme": "http", "status": 200, "timestamp": "2025-03-14T21:55:33.825576", "user": "ak-outpost-fd6fa081be4a4783b9abcb9c6afcf127", "user_agent": "goauthentik.io/outpost/2025.2.1"}

The same query done using ldapsearch works fine:

> ldapsearch -x -H ldap://10.229.46.151:389 -D 'cn=ldap-user,ou=users,dc=ldap,dc=goauthentik,dc=io' -w '<password>' -b 'ou=users,dc=ldap,dc=goauthentik,dc=io' '(memberOf=cn=customer,ou=groups,dc=ldap,dc=goauthentik,dc=io)'  'uid,cn,sn'

LDAP Outpost logs for the query above:

> {"attributes":["uid,cn,sn"],"baseDN":"ou=users,dc=ldap,dc=goauthentik,dc=io","bindDN":"cn=ldap-user,ou=users,dc=ldap,dc=goauthentik,dc=io","client":"10.11.127.15","event":"Search request","filter":"(memberOf=cn=customer,ou=groups,dc=ldap,dc=goauthentik,dc=io)","level":"info","requestId":"0e4bcf09-486e-42a8-ae9f-158b1518fea2","scope":"Whole Subtree","timestamp":"2025-03-14T22:03:59Z","took-ms":456}
> {"event":"hello'd","level":"trace","logger":"authentik.outpost.ak-api-controller","loop":"ws-health","timestamp":"2025-03-14T22:04:08Z"}

The difference between the 2 requests:
"attributes":["uid","cn","sn"]
"attributes":["uid,cn,sn"]

LDAP Outpost should be able to work in both cases and not throw an error.

-   authentik version: [e.g. 2025.2.1]
-   Deployment: [docker-compose]

### PR DESCRIPTION
**Pull request by dominic-r**
Closes https://github.com/goauthentik/authentik/issues/13539

When LDAP clients like Jira submit search requests with comma-separated attributes (e.g., ["uid,cn,sn"] instead of ["uid", "cn", "sn"]), the LDAP outpost would return an "Operations Error". Ths fix adds attribute normalization to properly handle both formats by splitting comma separated attributes into individual entries.

(happy pr 15k hehe)

## Details

REPLACE ME

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

File: internal/outpost/ldap/search/request_test.go [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+		},
+		{
+			name:           "No commas",
+			input:          []string{"uid", "cn", "sn"},
+			expectedOutput: []string{"uid", "cn", "sn"},
+		},
+		{
+			name:           "Single comma-separated string",
+			input:          []string{"uid,cn,sn"},
+			expectedOutput: []string{"uid", "cn", "sn"},
```
Comment (dominic-r) [inline internal/outpost/ldap/search/request_test.go:28]: According to https://datatracker.ietf.org/doc/html/rfc4511, it should be `SEQUENCE OF selector LDAPString` and `SEQUENCE` is a list of strings so this expected output would be correct

**Review by BeryJu — APPROVED** [review]
