### PR TITLE
web/admin: fix nested table pagination and search

### LINKED ISSUE #14489: First part of search is automatically inserted into RAC search
**Describe the bug**
When searching for the RAC application, after selecting the application, the first portion of the search term is inserted into the search bar of the RAC endpoint selection.

**To Reproduce**

1. Have more than 1 RAC endpoint configured
2. Search for the RAC application using the search bar
3. Click on the RAC application
4. See that the first 3 characters of the search term are inserted into the RAC endpoint selection

**Expected behavior**
After clicking on the RAC application, I'd expect for the endpoint search to be empty

**Screenshots**

Image

Image

**Logs**
Output of docker-compose logs or kubectl logs respectively

N/A

**Version and Deployment (please complete the following information):**

-   authentik version: 2025.2.4
-   Deployment: docker-compose

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

Fix issues with all tables using the same parameter names for search and pagination, causes issues on nested/modal tables

fixes #14489

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Review by kensternberg-authentik — APPROVED** [review]
The changes look unsurprising.  Are we sure "tagName" is sufficiently distinctive?

File: web/src/elements/table/Table.ts [hunk 1]
```diff
@@ -128,7 +128,7 @@ export abstract class Table<T> extends WithLicenseSummary(AKElement) implements
     data?: PaginatedResponse<T>;
 
     @property({ type: Number })
-    page = getURLParam("tablePage", 1);
+    page = getURLParam(`${this.tagName.toLowerCase()}-page`, 1);
```
Comment (GirlBossRush) [inline web/src/elements/table/Table.ts]:
```suggestion
    #pageParam = `${this.tagName.toLowerCase()}-page`;
    #searchParam = `${this.tagName.toLowerCase()}-search`;

    @property({ type: Number })
    public page? = getURLParam(`${this.#pageParam}`, 1);
```

File: web/src/elements/table/Table.ts [hunk 2]
```diff
@@ -220,7 +220,7 @@ export abstract class Table<T> extends WithLicenseSummary(AKElement) implements
             await this.fetch();
         });
         if (this.searchEnabled()) {
-            this.search = getURLParam("search", "");
+            this.search = getURLParam(`${this.tagName.toLowerCase()}-search`, "");
```
Comment (GirlBossRush) [inline web/src/elements/table/Table.ts]:
```suggestion
            this.search = getURLParam(`${this.#searchParam`, "");
```

File: web/src/elements/table/Table.ts [hunk 3]
```diff
@@ -475,14 +475,23 @@ export abstract class Table<T> extends WithLicenseSummary(AKElement) implements
...
+            updateURLParams({
+                [`${this.tagName.toLowerCase()}-page`]: changedProperties.get("page"),
+            });
+        }
+        if (changedProperties.has("search")) {
+            updateURLParams({
+                [`${this.tagName.toLowerCase()}-search`]: changedProperties.get("search"),
+            });
+        }
+    }
```
Comment (GirlBossRush) [inline web/src/elements/table/Table.ts]:
```suggestion
    protected willUpdate(changedProperties: PropertyValues<this>): void {
        const page = changedProperties.get("page");
        const search = changedProperties.get("search");

        updateURLParams({
            [`${this.#pageParam}`]: page,
            [`${this.#searchParam}`]: search,
        });
    }
```

Comment (BeryJu) [reply web/src/elements/table/Table.ts]: we can't do that since only one of the properties might change and then this would override the other one with undefined

**Review by GirlBossRush — APPROVED** [review]
Minor nits, good fixes :)

**Comment by dominic-r** [comment]
Should the schema have been updated for this PR as well? Locally, when running gen-build, a bunch of this are removed:
```
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
```

**Comment by BeryJu** [comment]
@dominic-r thats from a different pr and not intended

**Comment by BeryJu** [comment]
@dominic-r https://github.com/goauthentik/authentik/pull/15392

**Comment by dominic-r** [comment]
🎉
